# Production Environment Values
# Override default values for production deployment

global:
  environment: production

# Use specific stable version tags in production
image:
  repository: loadtest/app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

# Increase replicas and enable autoscaling for production
backend:
  replicaCount: 3
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 20
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

frontend:
  replicaCount: 3
  image:
    repository: loadtest/frontend
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

workers:
  replicaCount: 5
  autoscaling:
    enabled: true
    minReplicas: 5
    maxReplicas: 30
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 80
  env:
    WORKER_CONCURRENCY: "8"
    WORKER_PREFETCH_MULTIPLIER: "4"
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# Enable persistence with larger volumes for production
redis:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "fast-ssd"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  config:
    maxmemory: "512mb"

mongodb:
  persistence:
    enabled: true
    size: 50Gi
    storageClass: "fast-ssd"
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  # Set via external secrets or --set flags
  auth:
    password: ""
    rootPassword: ""

# Production ingress with TLS
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
  hosts:
    - host: loadtest.example.com
      paths:
        - path: /api
          pathType: Prefix
          backend: backend
        - path: /
          pathType: Prefix
          backend: frontend
  tls:
    - secretName: loadtest-prod-tls
      hosts:
        - loadtest.example.com

# Enable monitoring in production
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    labels:
      prometheus: kube-prometheus

# Enable Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Network policies for production
networkPolicy:
  enabled: true
