{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadtest-app.fullname" . }}-backend
  labels:
    {{- include "loadtest-app.componentLabels" (dict "component" "backend" "root" .) | nindent 4 }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "loadtest-app.componentSelectorLabels" (dict "component" "backend" "root" .) | nindent 4 }}
{{- end }}
