{{- if .Values.workers.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loadtest-app.fullname" . }}-worker
  labels:
    {{- include "loadtest-app.componentLabels" (dict "component" "worker" "root" .) | nindent 4 }}
spec:
  {{- if not .Values.workers.autoscaling.enabled }}
  replicas: {{ .Values.workers.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "loadtest-app.componentSelectorLabels" (dict "component" "worker" "root" .) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/backend/secret.yaml") . | sha256sum }}
        {{- with .Values.workers.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "loadtest-app.componentSelectorLabels" (dict "component" "worker" "root" .) | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "loadtest-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.workers.podSecurityContext | nindent 8 }}
      containers:
      - name: worker
        securityContext:
          {{- toYaml .Values.workers.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SERVICE_TYPE
          value: "worker"
        {{- range $key, $value := .Values.workers.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "loadtest-app.fullname" . }}-backend-config
        - secretRef:
            name: {{ include "loadtest-app.fullname" . }}-backend-secret
        resources:
          {{- toYaml .Values.workers.resources | nindent 10 }}
      {{- with .Values.workers.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workers.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workers.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
