{{- if and .Values.workers.enabled .Values.workers.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "loadtest-app.fullname" . }}-worker
  labels:
    {{- include "loadtest-app.componentLabels" (dict "component" "worker" "root" .) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "loadtest-app.fullname" . }}-worker
  minReplicas: {{ .Values.workers.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.workers.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.workers.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.workers.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.workers.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.workers.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
