{{- if and .Values.redis.enabled .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "loadtest-app.fullname" . }}-redis
  labels:
    {{- include "loadtest-app.componentLabels" (dict "component" "redis" "root" .) | nindent 4 }}
spec:
  accessModes: {{ .Values.redis.persistence.accessModes }}
  {{- if .Values.redis.persistence.storageClass }}
  storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size | quote }}
{{- end }}
